CREATE TABLE CentrodeCusto( 
      id  integer generated by default as identity    , 
      CentroCusto varchar  (20)   , 
      Descricao varchar  (100)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE Grupo( 
      id  integer generated by default as identity     NOT NULL , 
      CodGrupoPatrimonio varchar  (20)   , 
      tipoDepreciacao integer   , 
      valorDepreciacao float   , 
      column_5 integer   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE Local( 
      id  integer generated by default as identity    , 
      Descricao varchar  (100)   , 
      CentrodeCusto_id integer    NOT NULL , 
      Local varchar  (20)   , 
      responsavel varchar  (100)    NOT NULL , 
      chapa integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE movimentacao( 
      id  integer generated by default as identity     NOT NULL , 
      localAntigo integer    NOT NULL , 
      patrimonioId integer    NOT NULL , 
      dataInspecao date    NOT NULL , 
      Descricao blob sub_type 1   , 
      imagem varchar  (200)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE movimentacaoDepreciacao( 
      id  integer generated by default as identity     NOT NULL , 
      patrimonioId integer    NOT NULL , 
      dataDepreciacao integer    NOT NULL , 
      valor float    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE Patrimonio( 
      id  integer generated by default as identity    , 
      CodigodoPatrimonio varchar  (20)   , 
      descricao varchar  (100)    NOT NULL , 
      ativo integer   , 
      responsavel varchar  (100)   , 
      chapa integer   , 
      Local_id integer    NOT NULL , 
      Grupo_id integer    NOT NULL , 
      ValorOriginal float   , 
      ValorAtual float   , 
      DataEntrada date   , 
      imagem varchar  (200)   , 
      tido_baixa_id integer   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE tipo_baixa( 
      id  integer generated by default as identity     NOT NULL , 
      Descricao blob sub_type 1    NOT NULL , 
      observacao blob sub_type 1   , 
 PRIMARY KEY (id)) ; 

 
 CREATE UNIQUE INDEX unique_idx_CentrodeCusto_id ON CentrodeCusto COMPUTED BY (id);
 CREATE UNIQUE INDEX unique_idx_CentrodeCusto_CentroCusto ON CentrodeCusto COMPUTED BY (CentroCusto);
 CREATE UNIQUE INDEX unique_idx_Local_id ON Local COMPUTED BY (id);
 CREATE UNIQUE INDEX unique_idx_Patrimonio_id ON Patrimonio COMPUTED BY (id);
 CREATE UNIQUE INDEX unique_idx_Patrimonio_CodigodoPatrimonio ON Patrimonio COMPUTED BY (CodigodoPatrimonio);
  
 ALTER TABLE Local ADD CONSTRAINT fk_Local_1 FOREIGN KEY (CentrodeCusto_id) references CentrodeCusto(id); 
ALTER TABLE movimentacao ADD CONSTRAINT fk_movimentacao_1 FOREIGN KEY (localAntigo) references Local(id); 
ALTER TABLE movimentacao ADD CONSTRAINT fk_movimentacao_2 FOREIGN KEY (patrimonioId) references Patrimonio(id); 
ALTER TABLE movimentacaoDepreciacao ADD CONSTRAINT fk_movimentacaoDepreciacao_1 FOREIGN KEY (patrimonioId) references Patrimonio(id); 
ALTER TABLE Patrimonio ADD CONSTRAINT fk_Patrimonio_1 FOREIGN KEY (tido_baixa_id) references tipo_baixa(id); 
ALTER TABLE Patrimonio ADD CONSTRAINT fk_Patrimonio_2 FOREIGN KEY (Grupo_id) references Grupo(id); 
